version: '3'
services:
  rss-bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1 # 强制 Python 实时输出日志
      - STATE_FILE=/app/data/state.json
      - TZ=Asia/Shanghai
